language: python

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33

python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install https://github.com/pypa/virtualenv/tarball/develop
  - pip install tox

script:
  - tox -e $TOX_ENV


